INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (1, 'Cuenca', 'Tiene una poblacion de 505585 habitantes',1);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (2, 'Giron', 'Tiene una poblacion de 12607 habitantes',1);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (3, 'Gualaceo', 'Tiene una poblacion de 42709 habitantes',1);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (4, 'Sigsig', 'Tiene una poblacion de 26910 habitantes',1);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (5, 'San Fernando', 'Tiene una poblacion de 3993 habitantes',1);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (6, 'Santa Isabel', 'Tiene una poblacion de 18393 habitantes',1);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (7, 'Ponce Enriquez', 'Tiene una poblacion de 21998 habitantes',1);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (8, 'El Pan', 'Tiene una poblacion de 3036 habitantes',1);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (9, 'Giron', 'Tiene una poblacion de 12607 habitantes',1);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (10, 'Guachapala', 'Tiene una poblacion de 3409 habitantes',1);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (11, 'Gualaceo', 'Tiene una poblacion de 42709 habitantes',1);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (12, 'Nabon', 'Tiene una poblacion de 15892 habitantes',1);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (13, 'Oña', 'Tiene una poblacion de 3583 habitantes',1);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (14, 'Pucara', 'Tiene una poblacion de 10052 habitantes',1);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (15, 'Chordeleg', 'Tiene una poblacion de 12577 habitantes',1);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (16, 'Caluma', 'Tiene una poblacion de 505585 habitantes',2);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (17, 'Chillanes', 'Tiene una poblacion de 12607 habitantes',2);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (18, 'Chimbo', 'Tiene una poblacion de 42709 habitantes',2);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (19, 'Echeandia', 'Tiene una poblacion de 26910 habitantes',2);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (20, 'Guaranda', 'Tiene una poblacion de 3993 habitantes',2);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (21, 'Las Naves', 'Tiene una poblacion de 18393 habitantes',2);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (22, 'San Miguel', 'Tiene una poblacion de 21998 habitantes',2);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (23, 'Azogues', 'Tiene una poblacion de 505585 habitantes',3);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (24, 'Biblian', 'Tiene una poblacion de 12607 habitantes',3);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (25, 'Canar', 'Tiene una poblacion de 42709 habitantes',3);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (26, 'Deleg', 'Tiene una poblacion de 26910 habitantes',3);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (27, 'El Tambo', 'Tiene una poblacion de 3993 habitantes',3);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (28, 'La Troncal', 'Tiene una poblacion de 18393 habitantes',3);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (29, 'Suscal', 'Tiene una poblacion de 21998 habitantes',3);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (30, 'Tulcan', 'Tiene una poblacion de 505585 habitantes',4);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (31, 'Bolivar', 'Tiene una poblacion de 12607 habitantes',4);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (32, 'Espejo', 'Tiene una poblacion de 42709 habitantes',4);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (33, 'Mira', 'Tiene una poblacion de 26910 habitantes',4);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (34, 'Montufar', 'Tiene una poblacion de 3993 habitantes',4);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (35, 'San Pedro', 'Tiene una poblacion de 18393 habitantes',4);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (36, 'Riobamba', 'Tiene una poblacion de 3036 habitantes',5);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (37, 'Alausi', 'Tiene una poblacion de 12607 habitantes',5);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (38, 'Chambo', 'Tiene una poblacion de 3409 habitantes',5);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (39, 'Chunchi', 'Tiene una poblacion de 42709 habitantes',5);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (40, 'Colta', 'Tiene una poblacion de 15892 habitantes',5);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (41, 'Cumanda', 'Tiene una poblacion de 3583 habitantes',5);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (42, 'Guamote', 'Tiene una poblacion de 10052 habitantes',5);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (43, 'Guano', 'Tiene una poblacion de 12577 habitantes',5);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (44, 'Pallanta', 'Tiene una poblacion de 12577 habitantes',5);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (45, 'Penipe', 'Tiene una poblacion de 10052 habitantes',5);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (46, 'Latacunga', 'Tiene una poblacion de 3036 habitantes',6);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (47, 'La Mana', 'Tiene una poblacion de 12607 habitantes',6);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (48, 'Pujili', 'Tiene una poblacion de 3409 habitantes',6);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (49, 'Pangua', 'Tiene una poblacion de 42709 habitantes',6);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (50, 'Salcedo', 'Tiene una poblacion de 15892 habitantes',6);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (51, 'Saquisili', 'Tiene una poblacion de 3583 habitantes',6);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (52, 'Sigchos', 'Tiene una poblacion de 10052 habitantes',6);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (53, 'Ibarra', 'Tiene una poblacion de 12577 habitantes',7);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (54, 'Antonio Ante', 'Tiene una poblacion de 10052 habitantes',7);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (55, 'Cotacachi', 'Tiene una poblacion de 3583 habitantes',7);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (56, 'Otavalo', 'Tiene una poblacion de 15892 habitantes',7);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (57, 'Pimampiro', 'Tiene una poblacion de 42709 habitantes',7);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (58, 'Urcuqui', 'Tiene una poblacion de 3409 habitantes',7);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (59, 'Loja', 'Tiene una poblacion de 3036 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (60, 'Calvas', 'Tiene una poblacion de 12607 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (61, 'Catamayo', 'Tiene una poblacion de 3409 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (62, 'Celica', 'Tiene una poblacion de 42709 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (63, 'Chaguarpamba', 'Tiene una poblacion de 15892 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (64, 'Espindola', 'Tiene una poblacion de 3583 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (65, 'Gonzanama', 'Tiene una poblacion de 10052 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (66, 'Macara', 'Tiene una poblacion de 12577 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (67, 'Olmedo', 'Tiene una poblacion de 12577 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (68, 'Paltas', 'Tiene una poblacion de 10052 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (69, 'Pindal', 'Tiene una poblacion de 3036 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (70, 'Puyango', 'Tiene una poblacion de 12607 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (71, 'Quilanga', 'Tiene una poblacion de 3409 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (72, 'Saraguro', 'Tiene una poblacion de 42709 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (73, 'Sozoranga', 'Tiene una poblacion de 15892 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (74, 'Zapotillo', 'Tiene una poblacion de 3583 habitantes',8);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (75, 'Quito', 'Tiene una poblacion de 3036 habitantes',9);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (76, 'Cayambe', 'Tiene una poblacion de 12607 habitantes',9);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (77, 'Mejia', 'Tiene una poblacion de 3409 habitantes',9);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (78, 'Pedro Moncayo', 'Tiene una poblacion de 42709 habitantes',9);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (79, 'Pedro Vicente Maldonado', 'Tiene una poblacion de 15892 habitantes',9);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (80, 'Puerto Quito', 'Tiene una poblacion de 3583 habitantes',9);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (81, 'Ruminahui', 'Tiene una poblacion de 10052 habitantes',9);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (82, 'San Miguel', 'Tiene una poblacion de 12577 habitantes',9);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (83, 'Santo Domingo', 'Tiene una poblacion de 12577 habitantes',10);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (84, 'La Concordia', 'Tiene una poblacion de 10052 habitantes',10);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (85, 'Ambato', 'Tiene una poblacion de 12577 habitantes',11);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (86, 'Banos', 'Tiene una poblacion de 10052 habitantes',11);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (87, 'Cevallos', 'Tiene una poblacion de 3036 habitantes',11);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (88, 'Moncha', 'Tiene una poblacion de 12607 habitantes',11);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (89, 'Patate', 'Tiene una poblacion de 3409 habitantes',11);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (90, 'Pelileo', 'Tiene una poblacion de 42709 habitantes',11);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (91, 'Quero', 'Tiene una poblacion de 15892 habitantes',11);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (92, 'Santiago de Pillaro', 'Tiene una poblacion de 3583 habitantes',11);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (93, 'Tisaleo', 'Tiene una poblacion de 3583 habitantes',11);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (94, 'Machala', 'Tiene una poblacion de 3036 habitantes',12);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (95, 'Arenillas', 'Tiene una poblacion de 12607 habitantes',12);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (96, 'Atahualpa', 'Tiene una poblacion de 3409 habitantes',12);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (97, 'Balsas', 'Tiene una poblacion de 42709 habitantes',12);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (98, 'Chilla', 'Tiene una poblacion de 15892 habitantes',12);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (99, 'El Guabo', 'Tiene una poblacion de 3583 habitantes',12);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (100, 'Huaquillas', 'Tiene una poblacion de 10052 habitantes',12);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (101, 'Las Lajas', 'Tiene una poblacion de 12577 habitantes',12);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (102, 'Marcabelí', 'Tiene una poblacion de 12577 habitantes',12);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (103, 'Pasaje', 'Tiene una poblacion de 10052 habitantes',12);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (104, 'Pinas', 'Tiene una poblacion de 3036 habitantes',12);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (105, 'Portovelo', 'Tiene una poblacion de 12607 habitantes',12);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (106, 'Santa Rosa', 'Tiene una poblacion de 3409 habitantes',12);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (107, 'Zaruma', 'Tiene una poblacion de 42709 habitantes',12);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (108, 'Esmeraldas', 'Tiene una poblacion de 12607 habitantes',13);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (109, 'Atacames', 'Tiene una poblacion de 3409 habitantes',13);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (110, 'Eloy Alfaro', 'Tiene una poblacion de 42709 habitantes',13);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (111, 'Muisne', 'Tiene una poblacion de 15892 habitantes',13);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (112, 'Quininde', 'Tiene una poblacion de 3583 habitantes',13);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (113, 'Rioverde', 'Tiene una poblacion de 10052 habitantes',13);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (114, 'San Lorenzo', 'Tiene una poblacion de 12577 habitantes',13);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (115, 'Guayaquil', 'Tiene una poblacion de 12577 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (116, 'Alfredo Baquerizo Moreno', 'Tiene una poblacion de 10052 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (117, 'Balao', 'Tiene una poblacion de 3036 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (118, 'Balzar', 'Tiene una poblacion de 12607 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (119, 'Colimes', 'Tiene una poblacion de 3409 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (120, 'Daule', 'Tiene una poblacion de 42709 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (121, 'Duran', 'Tiene una poblacion de 15892 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (122, 'El Empalme', 'Tiene una poblacion de 3583 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (123, 'El Triunfo', 'Tiene una poblacion de 12577 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (124, 'General Antonio Elizalde', 'Tiene una poblacion de 10052 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (125, 'Isidro Ayora', 'Tiene una poblacion de 3036 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (126, 'Lomas de Sargentillo', 'Tiene una poblacion de 12607 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (127, 'Marcelino Maridueña', 'Tiene una poblacion de 3409 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (128, 'Milagro', 'Tiene una poblacion de 42709 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (129, 'Naranjal', 'Tiene una poblacion de 15892 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (130, 'Naranjito', 'Tiene una poblacion de 3583 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (131, 'Nobol', 'Tiene una poblacion de 12577 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (132, 'Palestina', 'Tiene una poblacion de 10052 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (133, 'Pedro Carbo', 'Tiene una poblacion de 3036 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (134, 'Playas', 'Tiene una poblacion de 12607 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (135, 'Satire', 'Tiene una poblacion de 3409 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (136, 'Samborondon', 'Tiene una poblacion de 42709 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (137, 'Santa Lucia', 'Tiene una poblacion de 15892 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (138, 'Simon Bolivar', 'Tiene una poblacion de 3583 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (139, 'Canton Yaguachi', 'Tiene una poblacion de 3583 habitantes',14);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (140, 'Babahoyo', 'Tiene una poblacion de 42709 habitantes',15);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (141, 'Baba', 'Tiene una poblacion de 15892 habitantes',15);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (142, 'Buena Fe', 'Tiene una poblacion de 3583 habitantes',15);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (143, 'Mocache', 'Tiene una poblacion de 12577 habitantes',15);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (144, 'Montalvo', 'Tiene una poblacion de 10052 habitantes',15);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (145, 'Palenque', 'Tiene una poblacion de 3036 habitantes',15);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (146, 'Puebloviejo', 'Tiene una poblacion de 12607 habitantes',15);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (147, 'Quevedo', 'Tiene una poblacion de 3409 habitantes',15);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (148, 'Quinsaloma', 'Tiene una poblacion de 42709 habitantes',15);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (149, 'Urdaneta', 'Tiene una poblacion de 3583 habitantes',15);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (150, 'Valencia', 'Tiene una poblacion de 12577 habitantes',15);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (151, 'Ventanas', 'Tiene una poblacion de 10052 habitantes',15);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (152, 'Vinces', 'Tiene una poblacion de 3036 habitantes',15);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (153, 'Portoviejo', 'Tiene una poblacion de 42709 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (154, '24 de Mayo', 'Tiene una poblacion de 15892 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (155, 'Bolivar', 'Tiene una poblacion de 3583 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (156, 'Chone', 'Tiene una poblacion de 12577 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (157, 'El Carmen', 'Tiene una poblacion de 10052 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (158, 'Flavio Alfaro', 'Tiene una poblacion de 3036 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (159, 'Jama', 'Tiene una poblacion de 12607 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (160, 'Jaramijo', 'Tiene una poblacion de 3409 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (161, 'Jipijapa', 'Tiene una poblacion de 42709 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (162, 'Junin', 'Tiene una poblacion de 3583 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (163, 'Manta', 'Tiene una poblacion de 12577 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (164, 'Montecristi', 'Tiene una poblacion de 10052 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (165, 'Olmedo', 'Tiene una poblacion de 3036 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (166, 'Pajan', 'Tiene una poblacion de 42709 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (167, 'Pedernales', 'Tiene una poblacion de 15892 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (168, 'Pichincha', 'Tiene una poblacion de 3583 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (169, 'Puerto Lopez', 'Tiene una poblacion de 12577 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (170, 'Rocafuerte', 'Tiene una poblacion de 10052 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (171, 'San Vicente', 'Tiene una poblacion de 3036 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (172, 'Santa Ana', 'Tiene una poblacion de 12607 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (173, 'Sucre', 'Tiene una poblacion de 3409 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (174, 'Tosagua', 'Tiene una poblacion de 42709 habitantes',16);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (175, 'Santa Elena', 'Tiene una poblacion de 12607 habitantes',17);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (176, 'La Libertad', 'Tiene una poblacion de 3409 habitantes',17);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (177, 'Salinas', 'Tiene una poblacion de 42709 habitantes',17);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (178, 'Morona', 'Tiene una poblacion de 42709 habitantes',18);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (179, 'Gualaquiza', 'Tiene una poblacion de 15892 habitantes',18);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (180, 'Huamboya', 'Tiene una poblacion de 3583 habitantes',18);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (181, 'Limon Indanza', 'Tiene una poblacion de 12577 habitantes',18);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (182, 'Logroño', 'Tiene una poblacion de 10052 habitantes',18);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (183, 'Pablo Sexto', 'Tiene una poblacion de 3036 habitantes',18);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (184, 'Palora', 'Tiene una poblacion de 12607 habitantes',18);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (185, 'San Juan Bosco', 'Tiene una poblacion de 3409 habitantes',18);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (186, 'Santiago de Mendez', 'Tiene una poblacion de 42709 habitantes',18);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (187, 'Sucua', 'Tiene una poblacion de 3583 habitantes',18);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (188, 'Taisha', 'Tiene una poblacion de 12577 habitantes',18);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (189, 'Tiwintza', 'Tiene una poblacion de 10052 habitantes',18);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (190, 'Tena', 'Tiene una poblacion de 12577 habitantes',19);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (191, 'Archidona', 'Tiene una poblacion de 10052 habitantes',19);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (192, 'Tola', 'Tiene una poblacion de 3036 habitantes',19);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (193, 'El Chaco', 'Tiene una poblacion de 12607 habitantes',19);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (194, 'Quijos', 'Tiene una poblacion de 3409 habitantes',19);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (195, 'San Juan Bosco', 'Tiene una poblacion de 3409 habitantes',20);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (196, 'Santiago de Mendez', 'Tiene una poblacion de 42709 habitantes',20);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (197, 'Sucua', 'Tiene una poblacion de 3583 habitantes',20);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (198, 'Taisha', 'Tiene una poblacion de 12577 habitantes',20);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (199, 'Pastaza', 'Tiene una poblacion de 15892 habitantes',21);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (200, 'Arajuno', 'Tiene una poblacion de 3583 habitantes',21);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (201, 'Mera', 'Tiene una poblacion de 12577 habitantes',21);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (202, 'Santa Clara', 'Tiene una poblacion de 10052 habitantes',21);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (203, 'Zamora', 'Tiene una poblacion de 12577 habitantes',22);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (204, 'Centinela del Condor', 'Tiene una poblacion de 10052 habitantes',22);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (205, 'Chinchipe', 'Tiene una poblacion de 3036 habitantes',22);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (206, 'El Pangui', 'Tiene una poblacion de 12607 habitantes',22);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (207, 'Nangaritza', 'Tiene una poblacion de 3409 habitantes',22);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (208, 'Palanda', 'Tiene una poblacion de 42709 habitantes',22);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (209, 'Paquisha', 'Tiene una poblacion de 3583 habitantes',22);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (210, 'Yacuambi', 'Tiene una poblacion de 12577 habitantes',22);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (211, 'Yantzaza', 'Tiene una poblacion de 10052 habitantes',22);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (212, 'San Cristobal', 'Tiene una poblacion de 12607 habitantes',23);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (213, 'Isabela', 'Tiene una poblacion de 3409 habitantes',23);
INSERT INTO `cantones` (`id`, `nombre`, `descripcion`,`fk_id`) VALUES (214, 'Santa Cruz', 'Tiene una poblacion de 42709 habitantes',23);

ALTER TABLE `cantones` ADD PRIMARY KEY (`id`);
ALTER TABLE `cantones` MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

